# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dorm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dorm_number', models.IntegerField(default=0)),
            ],
        ),
    ]
