# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 04:16
from __future__ import unicode_literals

import JNFLS.modules.accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dorms', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=40, null=True, unique=True)),
                ('alias', models.CharField(max_length=20, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars')),
                ('type', models.IntegerField(choices=[(0, '学生'), (1, '教师'), (2, '家长')], default=0)),
                ('first_name', models.CharField(blank=True, max_length=40, null=True)),
                ('last_name', models.CharField(blank=True, max_length=40, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_student_union', models.BooleanField(default=False)),
                ('is_head_teacher', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('my_dorm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dorms.Dorm')),
            ],
            options={
                'ordering': ['created'],
            },
            managers=[
                ('objects', JNFLS.modules.accounts.models.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='StudentUnionDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
