# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorms', '0001_initial'),
        ('accounts', '0002_auto_20170702_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='my_clubs',
        ),
        migrations.AddField(
            model_name='account',
            name='my_dorm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dorms.Dorm'),
        ),
    ]
