# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='board',
        ),
        migrations.RemoveField(
            model_name='post',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='post',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='reply_to',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
